# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadMagnet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("pdf_file_name", models.CharField(blank=True, max_length=500)),
                ("pdf_url", models.URLField(blank=True, max_length=500)),
                ("preview_image_name", models.CharField(blank=True, max_length=500)),
                ("preview_image_url", models.URLField(blank=True, max_length=500)),
                ("brevo_list_id", models.IntegerField(blank=True, help_text="Brevo list ID to add contacts to on submission.", null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead magnet",
                "verbose_name_plural": "Lead magnets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadMagnetSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lead_magnet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="lead_magnet.leadmagnet")),
            ],
            options={
                "verbose_name": "Lead magnet submission",
                "verbose_name_plural": "Lead magnet submissions",
                "ordering": ["-created_at"],
                "unique_together": {("lead_magnet", "email")},
            },
        ),
    ]
