# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead_magnet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadmagnet",
            name="brevo_template_id",
            field=models.IntegerField(
                blank=True,
                help_text="Brevo transactional template ID for the welcome email (e.g. 1 for 30-steam-activities). If set, the template is used instead of the default HTML.",
                null=True,
            ),
        ),
    ]
