# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead_magnet", "0002_leadmagnet_brevo_template_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadmagnet",
            name="email_only_delivery",
            field=models.BooleanField(
                default=False,
                help_text="If checked, frontend should use a different button label (e.g. 'Send me the guide') and not open/download the PDF after submit; guide is sent by email only.",
            ),
        ),
    ]
