# Generated by Django 4.2.24 on 2026-02-26 20:53

from django.db import migrations, models
import lead_magnet.models


class Migration(migrations.Migration):
    dependencies = [
        ("lead_magnet", "0003_leadmagnet_email_only_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadmagnet",
            name="benefits",
            field=models.JSONField(
                blank=True, default=lead_magnet.models._default_benefits
            ),
        ),
    ]
