# Generated by Django 4.2.23 on 2025-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="twitter_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
