# Generated by Django 4.2.23 on 2025-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="child_email",
            field=models.EmailField(
                blank=True,
                help_text="Child's email (for older students)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="child_first_name",
            field=models.CharField(
                blank=True, help_text="Child's first name", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="child_last_name",
            field=models.CharField(
                blank=True, help_text="Child's last name", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="child_phone",
            field=models.CharField(
                blank=True,
                help_text="Child's phone (for older students)",
                max_length=20,
            ),
        ),
    ]
