# Generated by Django 4.2.24 on 2025-11-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_role_parentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="last_performance_update",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last performance aggregate update",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="overall_assignment_average_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overall average assignment score percentage across all courses",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="overall_average_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Combined average of quiz and assignment scores",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="overall_quiz_average_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overall average quiz score percentage across all courses",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="total_assignments_completed",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total number of completed assignment submissions across all courses",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="total_quizzes_completed",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total number of completed quiz attempts across all courses",
            ),
        ),
    ]
