# Generated by Django 4.2.24 on 2025-11-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_studentprofile_last_performance_update_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentWeeklyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(help_text="Monday of the week (ISO week start)"),
                ),
                ("year", models.IntegerField(help_text="Year of the week")),
                (
                    "week_number",
                    models.IntegerField(help_text="ISO week number (1-53)"),
                ),
                (
                    "quiz_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average quiz score percentage for this week",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "quiz_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of quizzes completed this week"
                    ),
                ),
                (
                    "assignment_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average assignment score percentage for this week",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "assignment_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of assignments completed/graded this week",
                    ),
                ),
                (
                    "overall_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Combined weighted average of quiz and assignment scores for this week",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_performance",
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Weekly Performance",
                "verbose_name_plural": "Student Weekly Performances",
                "db_table": "student_weekly_performance",
                "ordering": ["-year", "-week_number"],
                "indexes": [
                    models.Index(
                        fields=["student_profile", "year", "week_number"],
                        name="student_wee_student_8d4400_idx",
                    ),
                    models.Index(
                        fields=["student_profile", "week_start_date"],
                        name="student_wee_student_759be9_idx",
                    ),
                ],
                "unique_together": {("student_profile", "year", "week_number")},
            },
        ),
    ]
