# Generated by Django 4.2+ - add timezone for scheduling (midnight checks per student)

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_studentweeklyperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone (e.g. Africa/Lagos, Asia/Shanghai). Used for scheduling and midnight checks.",
                max_length=63,
            ),
        ),
    ]
