# Generated by Django 4.2.24 on 2026-03-07 07:20

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_add_student_profile_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone (e.g. Africa/Lagos, Asia/Shanghai). Used for scheduling and midnight checks.",
                max_length=63,
                validators=[users.validators.validate_iana_timezone],
            ),
        ),
    ]
