# Generated by Cursor on 2026-03-26

from django.db import migrations, models
from django.core.validators import RegexValidator


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_studentprofile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_handle",
            field=models.SlugField(
                db_index=True,
                validators=[
                    RegexValidator(
                        regex=r"^[a-z0-9-]+$",
                        message="Public handle can only contain lowercase letters, numbers, and hyphens",
                    )
                ],
                help_text="Short unique handle for hosted app URLs (e.g. john243).",
                max_length=20,
                null=True,
                blank=True,
                unique=True,
            ),
        ),
    ]

