# Generated by Django 4.2.24 on 2026-03-30 05:43

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_admin_calendar_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="admin_calendar_timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone for Django admin dashboard calendar/timetable (e.g. America/Toronto). Empty = System Settings calendar timezone, then TIME_ZONE.",
                max_length=63,
                validators=[users.validators.validate_iana_timezone],
            ),
        ),
    ]
