# Generated by Django 4.2.24 on 2026-03-31 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_user_admin_calendar_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="compensation_basis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hourly", "Hourly"),
                    ("monthly", "Monthly"),
                    ("weekly", "Weekly"),
                    ("bi_weekly", "Bi-weekly"),
                    ("semi_monthly", "Semi-monthly"),
                    ("other", "Other"),
                ],
                help_text="How to interpret compensation_rate: hourly = per hour; monthly = per calendar month; bi_weekly / semi_monthly = per paycheck for that cadence (define consistently in ops docs).",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="compensation_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Compensation amount in USD; meaning depends on compensation_basis.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
