# Generated by Django 4.2.24 on 2026-03-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_teacherprofile_compensation"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="next_pay_day",
            field=models.DateField(
                blank=True,
                help_text="Operational next scheduled pay date for this teacher.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="pay_status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("pending", "Pending"),
                    ("failed", "Failed"),
                    ("processing", "Processing"),
                ],
                default="pending",
                help_text="Current payout status for the upcoming/current pay cycle.",
                max_length=20,
            ),
        ),
    ]
