# Generated by Django 4.2.24 on 2026-03-31 05:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_teacherprofile_payroll_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("processing", "Processing"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional payout amount for this cycle.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Scheduled payout date for this record.",
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank transfer"),
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        help_text="Settlement method used for this payout.",
                        max_length=30,
                    ),
                ),
                (
                    "receipt_image_url",
                    models.URLField(
                        blank=True, help_text="Optional receipt/proof image URL."
                    ),
                ),
                (
                    "third_party_payment_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional external payment link (processor transaction page).",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when payout was marked paid.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="users.teacherprofile",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_payouts",
                "ordering": ["-due_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["teacher_profile", "status"],
                        name="teacher_pay_teacher_aa9d44_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="teacher_pay_due_dat_7b0c3f_idx"
                    ),
                ],
            },
        ),
    ]
