# Generated by Django 4.2.24 on 2025-09-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="billing_interval",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="next_invoice_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="next_invoice_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
