# Generated by Django 4.2.24 on 2025-09-14 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0013_delete_courseenrollment"),
        ("billings", "0002_subscription_amount_subscription_billing_interval_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("stripe_price_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trialing", "Trialing"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete expired"),
                        ],
                        max_length=32,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("next_invoice_date", models.DateTimeField(blank=True, null=True)),
                (
                    "next_invoice_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                (
                    "billing_interval",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscribers",
                "indexes": [
                    models.Index(
                        fields=["user", "course"], name="billing_sub_user_id_220be2_idx"
                    ),
                    models.Index(
                        fields=["status"], name="billing_sub_status_e982dc_idx"
                    ),
                ],
                "unique_together": {("user", "course")},
            },
        ),
    ]
