# Generated by Django 4.2.24 on 2025-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billings", "0003_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribers",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("one_time", "One Time"),
                    ("trial", "Trial"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
    ]
