# Generated by Django 4.2.24 on 2025-09-15 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billings", "0004_subscribers_subscription_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
