# Generated by Django 4.2.24 on 2026-01-20 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0054_course_landing_page_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Program name (e.g., 'Math Program', 'Coding Program')",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="SEO-friendly URL slug (auto-generated from name if not provided)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Program description displayed on landing page"
                    ),
                ),
                (
                    "hero_media_url",
                    models.URLField(
                        blank=True,
                        help_text="GCS URL for hero image or video",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "hero_media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        help_text="Type of hero media (image or video)",
                        max_length=10,
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="Start Learning Today",
                        help_text="Call-to-action button text",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this program is active and visible",
                    ),
                ),
                (
                    "discount_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If True, users can enter a discount code (works with Stripe)",
                    ),
                ),
                (
                    "promotion_message",
                    models.TextField(
                        blank=True,
                        help_text="Promotion message to display on landing page",
                        null=True,
                    ),
                ),
                (
                    "promo_code",
                    models.CharField(
                        blank=True,
                        help_text="Stripe promotion code",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="If set, loads all courses with this category (mutually exclusive with courses field)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific courses to include (mutually exclusive with category field)",
                        related_name="programs",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="marketing_p_slug_970f5f_idx"),
                    models.Index(
                        fields=["is_active"], name="marketing_p_is_acti_50aa37_idx"
                    ),
                    models.Index(
                        fields=["category"], name="marketing_p_categor_6f0291_idx"
                    ),
                ],
            },
        ),
    ]
