# Generated by Django 4.2.24 on 2026-01-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="hero_features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of features displayed in hero section (e.g., ['Canadian Curriculum', 'Small Groups', 'Real Results'])",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="hero_subtitle",
            field=models.CharField(
                blank=True,
                help_text="Optional subtitle or tagline displayed below hero title",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="hero_title",
            field=models.CharField(
                blank=True,
                help_text="Main headline displayed over hero media (e.g., 'LIVE ONLINE MATH PROGRAMS')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="hero_value_propositions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of value propositions/marketing slogans (e.g., ['Build confidence. Improve results.', 'Track progress. Support your child's success.'])",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="program_overview_features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of program features with checkmarks for Program Overview section (e.g., ['Live Classes', 'Small Groups', 'Tests & Exams', 'Parent Reports', 'Canadian Curriculum'])",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="trust_strip_features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of trust indicators for Trust Strip section (e.g., ['Live Classes', 'Small Groups', 'Tests & Exams', 'Parent Reports', 'Canadian Curriculum'])",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="hero_media_url",
            field=models.URLField(
                blank=True,
                help_text="GCS URL for hero image or video (used as background)",
                max_length=500,
                null=True,
            ),
        ),
    ]
