# Generated by Django 4.2.24 on 2026-01-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0002_program_hero_features_program_hero_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="slug",
            field=models.SlugField(
                help_text="SEO-friendly URL slug (auto-generated from name if not provided). This becomes the marketing URL path (e.g., 'math' → https://www.sbtyacedemy.com/math)",
                max_length=200,
                unique=True,
            ),
        ),
    ]
