# Generated by Django 4.2.24 on 2026-08-10 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studycoach", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studysession",
            new_name="studycoach__student_ad79f3_idx",
            old_name="studycoach__student_7a0c1d_idx",
        ),
        migrations.RenameIndex(
            model_name="studysession",
            new_name="studycoach__lesson__92ccb0_idx",
            old_name="studycoach__lesson_3b8e2a_idx",
        ),
    ]
