# Generated by Django 4.2.24 on 2026-08-14 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0072_backfill_course_owner_memberships'),
        ('studycoach', '0002_rename_studycoach__student_7a0c1d_idx_studycoach__student_ad79f3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_bank', to='courses.lesson')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True/false'), ('short_answer', 'Short answer')], default='short_answer', max_length=32)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer', models.TextField()),
                ('hints', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], default='easy', max_length=16)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studycoach.coachbank')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['bank', 'order'], name='studycoach__bank_id_743140_idx')],
            },
        ),
    ]
