# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0072_backfill_course_owner_memberships"),
        ("studycoach", "0003_coach_bank_and_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="difficulty_mode",
            field=models.CharField(
                choices=[("easy", "Easy"), ("hard", "Hard"), ("auto", "Auto")],
                default="auto",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="CoachLessonMemory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("practice", "Practice"),
                            ("study_then_retake", "Study then retake"),
                            ("mastered", "Mastered"),
                        ],
                        default="practice",
                        max_length=32,
                    ),
                ),
                (
                    "auto_rung",
                    models.CharField(
                        choices=[
                            ("mix_easy", "Mix easy"),
                            ("mix_climb", "Mix climb"),
                            ("all_hard", "All hard"),
                            ("mastered", "Mastered"),
                        ],
                        default="mix_easy",
                        max_length=32,
                    ),
                ),
                ("next_mix", models.JSONField(blank=True, default=dict)),
                ("study_sources", models.JSONField(blank=True, default=list)),
                ("study_cleared_at", models.DateTimeField(blank=True, null=True)),
                ("last_feedback", models.JSONField(blank=True, default=dict)),
                ("last_band_scores", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coach_memories",
                        to="studycoach.studysession",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_coach_memories",
                        to="courses.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_coach_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="coachlessonmemory",
            index=models.Index(fields=["student", "-updated_at"], name="studycoach__student_mem_idx"),
        ),
        migrations.AddConstraint(
            model_name="coachlessonmemory",
            constraint=models.UniqueConstraint(
                fields=("student", "lesson"),
                name="studycoach_memory_student_lesson",
            ),
        ),
    ]
