# Generated by Django 4.2.24 on 2025-12-29 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorXBlockActionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("explain_more", "Explain More"),
                            ("give_examples", "Give Examples"),
                            ("simplify", "Simplify"),
                            ("summarize", "Summarize"),
                            ("generate_questions", "Generate Questions"),
                        ],
                        help_text="Type of block action",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for this action", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this action does"
                    ),
                ),
                (
                    "system_instruction",
                    models.TextField(
                        help_text="Base system instruction for this action. This is the foundation prompt that cannot be changed by users. Only admins can update this."
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Version number (auto-increments when updated)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this configuration is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created this configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tutorx_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who last modified this configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_tutorx_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TutorX Block Action Config",
                "verbose_name_plural": "TutorX Block Action Configs",
                "ordering": ["action_type"],
            },
        ),
        migrations.CreateModel(
            name="TutorXUserPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("explain_more", "Explain More"),
                            ("give_examples", "Give Examples"),
                            ("simplify", "Simplify"),
                            ("summarize", "Summarize"),
                            ("generate_questions", "Generate Questions"),
                        ],
                        help_text="Type of block action this prompt is for",
                        max_length=50,
                    ),
                ),
                (
                    "user_prompt",
                    models.TextField(
                        help_text="User's custom prompt. This will be combined with the base system instruction. Users can customize this to add their own instructions, preferences, or context."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name for this prompt (for user's reference)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description (for user's reference)",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default prompt for this action type for this user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this prompt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorx_user_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TutorX User Prompt",
                "verbose_name_plural": "TutorX User Prompts",
                "ordering": ["user", "action_type", "-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action_type", "is_default"],
                        name="tutorx_tuto_user_id_60dd8a_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tutorxuserprompt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user", "action_type"),
                name="unique_default_user_prompt_per_action",
            ),
        ),
        migrations.AddIndex(
            model_name="tutorxblockactionconfig",
            index=models.Index(
                fields=["action_type", "is_active"],
                name="tutorx_tuto_action__19da0d_idx",
            ),
        ),
    ]
