# Generated by Django 4.2.24 on 2025-12-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorx", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorxblockactionconfig",
            name="default_user_prompt",
            field=models.TextField(
                default="",
                help_text="Default user prompt template. Users see this initially and can customize it. Use placeholders: {block_content}, {context}, etc.",
            ),
            preserve_default=False,
        ),
    ]
