# Generated by Django 4.2.24 on 2025-12-29 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutorx", "0003_alter_tutorxblockactionconfig_default_user_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorXUserInstructionsDefaults",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("explain_more", "Explain More"),
                            ("give_examples", "Give Examples"),
                            ("simplify", "Simplify"),
                            ("summarize", "Summarize"),
                            ("generate_questions", "Generate Questions"),
                        ],
                        help_text="Type of block action",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for this action", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this action does"
                    ),
                ),
                (
                    "default_user_instruction",
                    models.TextField(
                        help_text="Default user instruction template. Users see this initially and can customize it. Use placeholders: {block_content}, {context}, etc."
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Version number (auto-increments when default_user_instruction changes)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this default is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created this default",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tutorx_user_instruction_defaults",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who last modified this default",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_tutorx_user_instruction_defaults",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TutorX User Instructions Default",
                "verbose_name_plural": "TutorX User Instructions Defaults",
                "ordering": ["action_type"],
                "indexes": [
                    models.Index(
                        fields=["action_type", "is_active"],
                        name="tutorx_tuto_action__83a575_idx",
                    )
                ],
            },
        ),
    ]
