# Generated by Django 4.2.24 on 2025-12-29 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutorx", "0004_tutorxuserinstructionsdefaults"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TutorXUserPrompt",
        ),
    ]
