# Generated by Django 4.2.24 on 2025-12-30 07:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0052_add_share_token_to_project_submission"),
        ("tutorx", "0005_delete_tutorxuserprompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorXBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Block"),
                            ("code", "Code Block"),
                            ("image", "Image Block"),
                            ("diagram", "Diagram Block"),
                        ],
                        help_text="Type of block (text, code, image, diagram)",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Block content. For code blocks, this is the code. For text blocks, this is the text content."
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Order of this block within the lesson (1, 2, 3, ...)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Block-specific metadata. For code blocks: {'language': 'python'}. For images: {'url': '...', 'caption': '...'}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Lesson this block belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorx_blocks",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "TutorX Block",
                "verbose_name_plural": "TutorX Blocks",
                "ordering": ["lesson", "order"],
                "indexes": [
                    models.Index(
                        fields=["lesson", "order"],
                        name="tutorx_tuto_lesson__bdf5d5_idx",
                    ),
                    models.Index(
                        fields=["block_type"], name="tutorx_tuto_block_t_435bc3_idx"
                    ),
                ],
                "unique_together": {("lesson", "order")},
            },
        ),
    ]
