# Generated by Django 4.2.24 on 2025-12-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorx", "0006_tutorxblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorxblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Block"),
                    ("code", "Code Block"),
                    ("image", "Image Block"),
                    ("diagram", "Diagram Block"),
                    ("table", "Table Block"),
                ],
                help_text="Type of block (text, code, image, diagram)",
                max_length=20,
            ),
        ),
    ]
