# Generated by Django 4.2.24 on 2026-01-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorx", "0007_alter_tutorxblock_block_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorxblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Block"),
                    ("code", "Code Block"),
                    ("image", "Image Block"),
                    ("diagram", "Diagram Block"),
                    ("table", "Table Block"),
                    ("divider", "Divider Block"),
                ],
                help_text="Type of block (text, code, image, diagram)",
                max_length=20,
            ),
        ),
    ]
