# Generated by Django 4.2.24 on 2026-03-12 20:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0062_courseassessment_module"),
        ("tutorx", "0008_alter_tutorxblock_block_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorxblockactionconfig",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("explain_more", "Explain More"),
                    ("give_examples", "Give Examples"),
                    ("simplify", "Simplify"),
                    ("summarize", "Summarize"),
                    ("generate_questions", "Generate Questions"),
                    ("draw_explainer_image", "Draw Explainer Image"),
                ],
                help_text="Type of block action",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tutorxuserinstructionsdefaults",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("explain_more", "Explain More"),
                    ("give_examples", "Give Examples"),
                    ("simplify", "Simplify"),
                    ("summarize", "Summarize"),
                    ("generate_questions", "Generate Questions"),
                    ("draw_explainer_image", "Draw Explainer Image"),
                ],
                help_text="Type of block action",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="InteractiveVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio_video_material",
                    models.ForeignKey(
                        blank=True,
                        help_text="Underlying audio/video material (HLS or normal file)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tutorx_interactive_videos",
                        to="courses.audiovideomaterial",
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        help_text="TutorX lesson this interactive video belongs to (type=tutorx)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactive_video",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interactive Video (TutorX)",
                "verbose_name_plural": "Interactive Videos (TutorX)",
            },
        ),
        migrations.CreateModel(
            name="InteractiveEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("pop_quiz", "Multiple choice"),
                            ("yes_no", "Yes / No"),
                            ("true_false", "True / False"),
                            ("essay", "Essay"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp_seconds", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("prompt", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                ("options", models.JSONField(blank=True, null=True)),
                ("correct_option_index", models.IntegerField(blank=True, null=True)),
                ("yes_label", models.CharField(blank=True, max_length=50)),
                ("no_label", models.CharField(blank=True, max_length=50)),
                ("explanation_yes", models.TextField(blank=True)),
                ("explanation_no", models.TextField(blank=True)),
                ("correct_answer", models.BooleanField(blank=True, null=True)),
                (
                    "interactive_video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tutorx.interactivevideo",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp_seconds", "id"],
            },
        ),
    ]
