# Generated by Django 4.2.24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorx", "0009_alter_tutorxblockactionconfig_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactiveevent",
            name="model_answer",
            field=models.TextField(blank=True),
        ),
    ]
