# Generated by Django 4.2.23 on 2025-09-02 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDashboardSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "live_lessons_limit",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of live lessons to show in upcoming events section",
                    ),
                ),
                (
                    "continue_learning_limit",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Number of lessons to show in continue learning section",
                    ),
                ),
                (
                    "show_today_only",
                    models.BooleanField(
                        default=True,
                        help_text="If True: show only today's events, If False: show all upcoming events",
                    ),
                ),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("light", "Light Theme"),
                            ("dark", "Dark Theme"),
                            ("auto", "Auto (System)"),
                        ],
                        default="auto",
                        help_text="Dashboard theme preference",
                        max_length=20,
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable dashboard notifications"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Dashboard Settings",
                "verbose_name_plural": "User Dashboard Settings",
                "ordering": ["-updated_at"],
            },
        ),
    ]
