# Generated by Django 4.2.24 on 2025-09-10 15:59

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "monthly_price_markup_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Percentage markup for monthly payments compared to one-time payment",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_students_per_course",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Default maximum students allowed per course",
                    ),
                ),
                (
                    "default_course_duration_weeks",
                    models.PositiveIntegerField(
                        default=8, help_text="Default course duration in weeks"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course Settings",
                "verbose_name_plural": "Course Settings",
            },
        ),
    ]
