# Generated by Django 4.2.24 on 2025-09-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_coursesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesettings",
            name="enable_trial_period",
            field=models.BooleanField(
                default=True, help_text="Enable trial period for courses"
            ),
        ),
        migrations.AddField(
            model_name="coursesettings",
            name="trial_period_days",
            field=models.PositiveIntegerField(
                default=14, help_text="Trial period duration in days"
            ),
        ),
    ]
