# Generated by Django 4.2.24 on 2025-09-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_coursesettings_enable_trial_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesettings",
            name="who_sets_price",
            field=models.CharField(
                choices=[
                    ("admin", "Admin Only"),
                    ("teacher", "Teachers Only"),
                    ("both", "Both Admin and Teachers"),
                ],
                default="admin",
                help_text="Who can set course prices - Admin, Teachers, or Both",
                max_length=10,
            ),
        ),
    ]
