# Generated by Django 4.2.24 on 2025-12-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0005_userdashboardsettings_auto_grade_multiple_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdashboardsettings",
            name="ide_url",
            field=models.URLField(
                blank=True,
                default="https://trinket.io",
                help_text="Default URL for IDE (teachers only)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="virtual_lab_url",
            field=models.URLField(
                blank=True,
                default="https://phet.colorado.edu",
                help_text="Default URL for virtual lab (teachers only)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="userdashboardsettings",
            name="whiteboard_url",
            field=models.URLField(
                blank=True,
                default="https://www.tldraw.com",
                help_text="Default URL for interactive whiteboard (teachers only)",
                max_length=500,
            ),
        ),
    ]
