# Generated by Django 4.2.24 on 2025-12-01 00:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_userdashboardsettings_ide_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomToolDefaults",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "whiteboard_url",
                    models.URLField(
                        default="https://www.tldraw.com",
                        help_text="Default URL for interactive whiteboard",
                        max_length=500,
                    ),
                ),
                (
                    "ide_url",
                    models.URLField(
                        default="https://trinket.io",
                        help_text="Default URL for IDE",
                        max_length=500,
                    ),
                ),
                (
                    "virtual_lab_url",
                    models.URLField(
                        default="https://phet.colorado.edu",
                        help_text="Default URL for virtual lab",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Classroom Tool Defaults",
                "verbose_name_plural": "Classroom Tool Defaults",
                "ordering": ["-updated_at"],
            },
        ),
    ]
