# Generated by Django 4.2.24 on 2025-12-29 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("settings", "0007_classroomtooldefaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTutorXInstruction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("explain_more", "Explain More"),
                            ("give_examples", "Give Examples"),
                            ("simplify", "Simplify"),
                            ("summarize", "Summarize"),
                            ("generate_questions", "Generate Questions"),
                        ],
                        help_text="Type of block action this instruction is for",
                        max_length=50,
                    ),
                ),
                (
                    "user_instruction",
                    models.TextField(
                        help_text="User's custom instruction. Use placeholders: {block_content}, {context}, etc."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this instruction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorx_instructions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User TutorX Instruction",
                "verbose_name_plural": "User TutorX Instructions",
                "ordering": ["user", "action_type"],
                "indexes": [
                    models.Index(
                        fields=["user", "action_type"],
                        name="settings_us_user_id_172788_idx",
                    )
                ],
                "unique_together": {("user", "action_type")},
            },
        ),
    ]
