# Generated by Django 4.2.24 on 2026-03-30 05:43

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0009_systemsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="calendar_timezone",
            field=models.CharField(
                default="UTC",
                help_text="Default IANA timezone for weekly ClassSession wall times and the admin timetable when the logged-in user has not set Admin calendar timezone (e.g. America/Toronto, Africa/Lagos).",
                max_length=63,
                validators=[users.validators.validate_iana_timezone],
            ),
        ),
    ]
