# Generated by Django 4.2.23 on 2025-08-21 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Note title", max_length=200)),
                ("content", models.TextField(help_text="Note content")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("lesson", "Lesson Specific"),
                            ("idea", "Idea"),
                            ("reminder", "Reminder"),
                            ("issue", "Issue"),
                        ],
                        default="general",
                        help_text="Note category",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional lesson this note is linked to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="courses.lesson",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher who created this note",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["course", "teacher"],
                        name="courses_not_course__cbe6db_idx",
                    ),
                    models.Index(
                        fields=["lesson", "category"],
                        name="courses_not_lesson__c45088_idx",
                    ),
                    models.Index(
                        fields=["-updated_at"], name="courses_not_updated_c72813_idx"
                    ),
                ],
            },
        ),
    ]
