# Generated by Django 4.2.23 on 2025-08-22 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseIntroduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overview", models.TextField(help_text="Detailed course description")),
                (
                    "learning_objectives",
                    models.JSONField(
                        default=list, help_text="List of learning objectives"
                    ),
                ),
                (
                    "prerequisites",
                    models.TextField(
                        blank=True,
                        help_text="What students should know before starting",
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        default=8, help_text="Course duration in weeks"
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=12, help_text="Maximum number of students"
                    ),
                ),
                (
                    "sessions_per_week",
                    models.PositiveIntegerField(
                        default=2, help_text="Number of sessions per week"
                    ),
                ),
                (
                    "total_projects",
                    models.PositiveIntegerField(
                        default=5, help_text="Number of projects students will create"
                    ),
                ),
                (
                    "value_propositions",
                    models.JSONField(default=list, help_text="List of course benefits"),
                ),
                (
                    "reviews",
                    models.JSONField(
                        default=list, help_text="Student reviews and ratings"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="introduction",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Introduction",
                "verbose_name_plural": "Course Introductions",
            },
        ),
    ]
