# Generated by Django 4.2.23 on 2025-08-25 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="duration",
        ),
    ]
