# Generated by Django 4.2.23 on 2025-08-22 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_courseintroduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="audio_url",
            field=models.URLField(
                blank=True, help_text="Audio URL for video/audio lessons", null=True
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="live_class_date",
            field=models.DateTimeField(
                blank=True, help_text="Scheduled date for live class", null=True
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="live_class_duration",
            field=models.IntegerField(
                blank=True,
                help_text="Live class duration in minutes",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(480),
                ],
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="live_class_status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                help_text="Current status of live class",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="text_content",
            field=models.TextField(
                blank=True, help_text="Rich text content for text lessons", null=True
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="Video URL for video/audio lessons", null=True
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.JSONField(
                default=dict,
                help_text="Additional type-specific lesson content and configuration",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="type",
            field=models.CharField(
                choices=[
                    ("live_class", "Live Class"),
                    ("video_audio", "Video/Audio Lesson"),
                    ("text_lesson", "Text Lesson"),
                ],
                max_length=20,
            ),
        ),
    ]
