# Generated by Django 4.2.23 on 2025-08-25 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_duration_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="schedule",
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Session name (e.g., 'Session 1', 'Morning Session')",
                        max_length=100,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of the week (0=Monday, 6=Sunday)",
                    ),
                ),
                ("start_time", models.TimeField(help_text="Session start time")),
                ("end_time", models.TimeField(help_text="Session end time")),
                (
                    "session_number",
                    models.PositiveIntegerField(
                        help_text="Order of this session (1, 2, 3...)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this session is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_instance",
                    models.ForeignKey(
                        help_text="The class this session belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="courses.class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Session",
                "verbose_name_plural": "Class Sessions",
                "db_table": "class_sessions",
                "ordering": ["class_instance", "session_number", "day_of_week"],
                "unique_together": {("class_instance", "session_number")},
            },
        ),
    ]
