# Generated by Django 4.2.23 on 2025-08-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_lesson_audio_url_lesson_live_class_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
