# Generated by Django 4.2.23 on 2025-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_remove_class_schedule_classsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="materials",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of lesson materials, resources, and attachments",
            ),
        ),
    ]
