# Generated by Django 4.2.23 on 2025-08-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_initial"),
        ("courses", "0005_lesson_materials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.enrolledcourse"
            ),
        ),
    ]
