# Generated by Django 4.2.23 on 2025-08-22 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_lesson_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="live_class_duration",
        ),
    ]
