# Generated by Django 4.2.23 on 2025-08-27 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_alter_quizattempt_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Material title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Material description"),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("link", "External Link"),
                            ("image", "Image"),
                            ("pdf", "PDF"),
                            ("presentation", "Presentation"),
                            ("worksheet", "Worksheet"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True, help_text="URL to the material file", null=True
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "file_extension",
                    models.CharField(
                        blank=True,
                        help_text="File extension (e.g., pdf, docx)",
                        max_length=10,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this material is required before class",
                    ),
                ),
                (
                    "is_downloadable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether students can download this material",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order of materials"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_materials",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "order"],
                "indexes": [
                    models.Index(
                        fields=["lesson", "material_type"],
                        name="courses_les_lesson__34eb31_idx",
                    ),
                    models.Index(
                        fields=["is_required"], name="courses_les_is_requ_6e9bca_idx"
                    ),
                ],
                "unique_together": {("lesson", "order")},
            },
        ),
    ]
