# Generated by Django 4.2.23 on 2025-08-22 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0006_remove_lesson_live_class_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the class (e.g., 'Morning Group A')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the class"
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of students allowed in this class",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        help_text="Class schedule (e.g., 'Mon/Wed 9:00 AM')",
                        max_length=200,
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, help_text="Online meeting link for virtual classes"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the class is currently active"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Class start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Class end date", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course this class is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="courses.course",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Students enrolled in this class",
                        limit_choices_to={"role": "student"},
                        related_name="enrolled_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher managing this class",
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taught_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "db_table": "classes",
                "ordering": ["course__title", "name"],
            },
        ),
    ]
