# Generated by Django 4.2.23 on 2025-08-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_lessonmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="grading_history",
            field=models.JSONField(
                default=list,
                help_text="Audit trail of grading changes and enhancements",
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="is_teacher_graded",
            field=models.BooleanField(
                default=False,
                help_text="Has teacher manually graded or enhanced this quiz?",
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="teacher_grade_data",
            field=models.JSONField(
                default=dict,
                help_text="Teacher's manual grading data (overrides auto-calculated if present)",
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["is_teacher_graded"], name="courses_qui_is_teac_1fc10a_idx"
            ),
        ),
    ]
