# Generated by Django 4.2.23 on 2025-08-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_enrolledcourse"),
        ("users", "0002_studentprofile_child_email_and_more"),
        ("courses", "0007_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enrolled_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students enrolled in this course",
                related_name="enrolled_courses",
                through="student.EnrolledCourse",
                to="users.studentprofile",
            ),
        ),
    ]
