# Generated by Django 4.2.23 on 2025-08-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_enhance_quiz_attempt_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="started_at",
            field=models.DateTimeField(),
        ),
    ]
