# Generated by Django 4.2.23 on 2025-08-23 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_course_enrolled_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Event title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Event description"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson"),
                            ("meeting", "Meeting"),
                            ("break", "Break"),
                        ],
                        default="lesson",
                        help_text="Type of event",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="Event start time")),
                ("end_time", models.DateTimeField(help_text="Event end time")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_instance",
                    models.ForeignKey(
                        help_text="The class this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="courses.class",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated lesson (if event type is lesson)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "class_events",
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["class_instance", "start_time"],
                        name="class_event_class_i_4ce758_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="class_event_event_t_4c8a97_idx"
                    ),
                    models.Index(
                        fields=["start_time"], name="class_event_start_t_44477f_idx"
                    ),
                ],
            },
        ),
    ]
