# Generated by Django 4.2.23 on 2025-09-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_fix_started_at_auto_now_add"),
    ]

    operations = [
        migrations.AddField(
            model_name="classevent",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("live", "Live Lesson"),
                    ("text", "Text Lesson"),
                    ("video", "Video Lesson"),
                    ("audio", "Audio Lesson"),
                    ("interactive", "Interactive Lesson"),
                ],
                default="text",
                help_text="Type of lesson (live, text, video, audio, interactive)",
                max_length=20,
            ),
        ),
    ]
