# Generated by Django 4.2.23 on 2025-08-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_classevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="classevent",
            name="meeting_id",
            field=models.CharField(
                blank=True, help_text="Meeting ID or room number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="classevent",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Meeting link for live classes (Google Meet, Zoom, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="classevent",
            name="meeting_password",
            field=models.CharField(
                blank=True, help_text="Meeting password if required", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="classevent",
            name="meeting_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google-meet", "Google Meet"),
                    ("zoom", "Zoom"),
                    ("other", "Other"),
                ],
                help_text="Platform for live class meetings",
                max_length=20,
                null=True,
            ),
        ),
    ]
