# Generated by Django 4.2.24 on 2025-09-11 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_add_lesson_type_to_classevent"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lessonprogress",
            name="courses_les_enrollm_0e4f7b_idx",
        ),
        migrations.RemoveIndex(
            model_name="lessonprogress",
            name="courses_les_lesson__b05e6f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="LessonProgress",
        ),
    ]
