# Generated by Django 4.2.24 on 2025-09-11 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_add_lesson_type_to_classevent"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name="lessonprogress",
            index_together=None,
        ),
        migrations.DeleteModel(
            name="LessonProgress",
        ),
    ]
