# Generated by Django 4.2.23 on 2025-08-24 20:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_add_meeting_fields_to_class_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(
                        help_text="Student's display name", max_length=100
                    ),
                ),
                (
                    "student_age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Student's age when review was written",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(18),
                        ],
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_text", models.TextField(help_text="Review content")),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Admin verified this is a real review"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show this review prominently on course details",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["course", "-created_at"],
                        name="courses_cou_course__845eb3_idx",
                    ),
                    models.Index(
                        fields=["course", "is_featured"],
                        name="courses_cou_course__55c370_idx",
                    ),
                    models.Index(
                        fields=["rating"], name="courses_cou_rating_4bf87d_idx"
                    ),
                ],
            },
        ),
    ]
