# Generated by Django 4.2.24 on 2025-09-13 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_update_quiz_attempt_enrollment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseEnrollment",
        ),
    ]
