# Generated by Django 4.2.24 on 2025-09-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_delete_courseenrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Course category name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Course category description"),
                ),
            ],
            options={
                "verbose_name": "Course Category",
                "verbose_name_plural": "Course Categories",
                "ordering": ["name"],
            },
        ),
    ]
