# Generated by Django 4.2.24 on 2025-09-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_coursecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_free",
            field=models.BooleanField(
                default=False, help_text="Whether this course is free to access"
            ),
        ),
    ]
