# Generated by Django 4.2.24 on 2025-09-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_course_is_free"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursereview",
            name="parent_name",
            field=models.CharField(
                blank=True,
                help_text="Parent's name for testimonials (e.g., 'Sarah M.', 'Emily Chen')",
                max_length=100,
            ),
        ),
    ]
