# Generated by Django 4.2.24 on 2025-09-22 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0016_coursereview_parent_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("instructions", models.TextField()),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("link", "Link/URL"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("file", "File Upload"),
                            ("note", "Text Note"),
                            ("code", "Code"),
                            ("presentation", "Presentation"),
                        ],
                        help_text="Type of submission expected from students",
                        max_length=20,
                    ),
                ),
                (
                    "allowed_file_types",
                    models.JSONField(
                        blank=True, default=list, help_text="Allowed file extensions"
                    ),
                ),
                ("points", models.PositiveIntegerField(default=100)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("SUBMITTED", "Submitted"),
                            ("RETURNED", "Returned"),
                            ("GRADED", "Graded"),
                        ],
                        default="ASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Submission content (text, notes, code)"
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True, help_text="URL to uploaded file in cloud storage"
                    ),
                ),
                ("reflection", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("points_earned", models.FloatField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "feedback_response",
                    models.TextField(
                        blank=True, help_text="Student's response to teacher feedback"
                    ),
                ),
                (
                    "feedback_checked",
                    models.BooleanField(
                        default=False, help_text="Whether student has seen the feedback"
                    ),
                ),
                (
                    "feedback_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When student last checked feedback",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="courses.project",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-created_at"],
                "unique_together": {("project", "student")},
            },
        ),
    ]
