# Generated by Django 4.2.24 on 2025-09-28 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0019_projectplatform"),
    ]

    operations = [
        migrations.AddField(
            model_name="classevent",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated project (if event type is project)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.project",
            ),
        ),
        migrations.AlterField(
            model_name="classevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("meeting", "Meeting"),
                    ("project", "Project"),
                    ("break", "Break"),
                ],
                default="lesson",
                help_text="Type of event",
                max_length=20,
            ),
        ),
    ]
