# Generated by Django 4.2.24 on 2025-09-29 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0020_classevent_project_alter_classevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="classevent",
            name="project_platform",
            field=models.ForeignKey(
                blank=True,
                help_text="Platform for project events",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.projectplatform",
            ),
        ),
    ]
