# Generated by Django 4.2.24 on 2025-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_classevent_project_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="classevent",
            name="due_date",
            field=models.DateTimeField(
                blank=True, help_text="Project due date (for project events)", null=True
            ),
        ),
        migrations.AddField(
            model_name="classevent",
            name="project_title",
            field=models.CharField(
                blank=True,
                help_text="Project title (cached for display purposes)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="classevent",
            name="submission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("link", "Link/URL"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("file", "File Upload"),
                    ("note", "Text Note"),
                    ("code", "Code"),
                    ("presentation", "Presentation"),
                ],
                help_text="Expected submission type for project events",
                max_length=20,
                null=True,
            ),
        ),
    ]
