# Generated by Django 4.2.24 on 2025-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0022_classevent_due_date_classevent_project_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classevent",
            name="lesson_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("live", "Live Lesson"),
                    ("text", "Text Lesson"),
                    ("video", "Video Lesson"),
                    ("audio", "Audio Lesson"),
                    ("interactive", "Interactive Lesson"),
                ],
                default="text",
                help_text="Type of lesson (live, text, video, audio, interactive)",
                max_length=20,
                null=True,
            ),
        ),
    ]
