# Generated by Django 4.2.24 on 2025-09-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0023_alter_classevent_lesson_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classevent",
            name="end_time",
            field=models.DateTimeField(
                blank=True, help_text="Event end time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="classevent",
            name="start_time",
            field=models.DateTimeField(
                blank=True, help_text="Event start time", null=True
            ),
        ),
    ]
