# Generated by Django 4.2.24 on 2025-10-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0024_alter_classevent_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("graded", "Graded"),
                ],
                default="draft",
                help_text="Submission status: draft, submitted, or graded",
                max_length=20,
            ),
        ),
    ]
