# Generated by Django 4.2.24 on 2025-10-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0025_assignmentsubmission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("teacher_draft", "Teacher Draft"),
                    ("graded", "Graded"),
                ],
                default="draft",
                help_text="Submission status: draft, submitted, teacher_draft, or graded",
                max_length=20,
            ),
        ),
    ]
