# Generated by Django 4.2.24 on 2025-10-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0026_alter_assignmentsubmission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="is_teacher_draft",
            field=models.BooleanField(
                default=False,
                help_text="Is teacher currently working on grading this submission?",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("graded", "Graded"),
                ],
                default="draft",
                help_text="Submission status: draft, submitted, or graded",
                max_length=20,
            ),
        ),
    ]
