# Generated by Django 4.2.24 on 2025-10-16 14:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0027_assignmentsubmission_is_teacher_draft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonmaterial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("link", "External Link"),
                    ("image", "Image"),
                    ("pdf", "PDF"),
                    ("presentation", "Presentation"),
                    ("worksheet", "Worksheet"),
                    ("book", "Book"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BookPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        help_text="Page number within the book"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Page title (optional)", max_length=200
                    ),
                ),
                ("content", models.TextField(help_text="Page content")),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="Page image URL", null=True),
                ),
                (
                    "audio_url",
                    models.URLField(blank=True, help_text="Page audio URL", null=True),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Is this page required reading?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book_material",
                    models.ForeignKey(
                        limit_choices_to={"material_type": "book"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_pages",
                        to="courses.lessonmaterial",
                    ),
                ),
            ],
            options={
                "ordering": ["book_material", "page_number"],
                "indexes": [
                    models.Index(
                        fields=["book_material", "page_number"],
                        name="courses_boo_book_ma_399f0f_idx",
                    ),
                    models.Index(
                        fields=["is_required"], name="courses_boo_is_requ_266fe9_idx"
                    ),
                ],
                "unique_together": {("book_material", "page_number")},
            },
        ),
    ]
