# Generated by Django 4.2.24 on 2025-10-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0028_alter_lessonmaterial_material_type_bookpage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonmaterial",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="lessonmaterial",
            name="courses_les_lesson__34eb31_idx",
        ),
        migrations.AlterUniqueTogether(
            name="lessonmaterial",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="lessonmaterial",
            name="lessons",
            field=models.ManyToManyField(
                blank=True, related_name="lesson_materials", to="courses.lesson"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonmaterial",
            index=models.Index(
                fields=["material_type"], name="courses_les_materia_74a009_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="lessonmaterial",
            name="lesson",
        ),
    ]
