# Generated by Django 4.2.24 on 2025-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0029_lesson_material_many_to_many"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonmaterial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("link", "External Link"),
                    ("image", "Image"),
                    ("pdf", "PDF"),
                    ("presentation", "Presentation"),
                    ("worksheet", "Worksheet"),
                    ("book", "Book"),
                    ("note", "Note"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
