# Generated by Django 4.2.24 on 2025-11-08 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0031_alter_prerequisites_text_to_jsonfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="URL of the video (YouTube or other)", unique=True
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        blank=True,
                        help_text="Video ID (e.g., YouTube video ID)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_youtube",
                    models.BooleanField(
                        default=False, help_text="Whether this is a YouTube video"
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True,
                        help_text="Full transcript text (if transcribed)",
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Language code of transcript (e.g., 'en', 'es')",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "language_name",
                    models.CharField(
                        blank=True,
                        help_text="Language name (e.g., 'English')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "method_used",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("youtube_api", "YouTube Transcript API"),
                            ("vertex_ai", "Vertex AI"),
                        ],
                        help_text="Method used to transcribe the video (if transcribed)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "transcript_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Length of transcript in characters",
                        null=True,
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Word count of transcript", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transcribed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the transcription was created (if transcribed)",
                        null=True,
                    ),
                ),
                (
                    "lesson_material",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to LessonMaterial if this is part of a lesson",
                        limit_choices_to={"material_type": "video"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_data",
                        to="courses.lessonmaterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Material",
                "verbose_name_plural": "Video Materials",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["video_url"], name="courses_vid_video_u_a594a3_idx"
                    ),
                    models.Index(
                        fields=["video_id"], name="courses_vid_video_i_54645e_idx"
                    ),
                    models.Index(
                        fields=["is_youtube"], name="courses_vid_is_yout_fe514e_idx"
                    ),
                    models.Index(
                        fields=["method_used"], name="courses_vid_method__b78e4f_idx"
                    ),
                    models.Index(
                        fields=["lesson_material"],
                        name="courses_vid_lesson__b8c2dd_idx",
                    ),
                ],
            },
        ),
    ]
