# Generated by Django 4.2.24 on 2025-11-09 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0032_videomaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Stored filename in GCS (e.g., 'documents/uuid-filename.pdf')",
                        max_length=255,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename from user upload (e.g., 'My Lesson Notes.pdf')",
                        max_length=255,
                    ),
                ),
                ("file_url", models.URLField(help_text="Full GCS URL to the document")),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "file_extension",
                    models.CharField(
                        help_text="File extension (e.g., 'pdf', 'docx', 'doc', 'txt')",
                        max_length=10,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="MIME type (e.g., 'application/pdf', 'application/msword')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson_material",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to LessonMaterial if this is part of a lesson",
                        limit_choices_to={"material_type": "document"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_data",
                        to="courses.lessonmaterial",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher who uploaded this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Material",
                "verbose_name_plural": "Document Materials",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["file_url"], name="courses_doc_file_ur_51c0af_idx"
                    ),
                    models.Index(
                        fields=["file_extension"], name="courses_doc_file_ex_4d2dd9_idx"
                    ),
                    models.Index(
                        fields=["mime_type"], name="courses_doc_mime_ty_7c6d1f_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="courses_doc_uploade_568dc2_idx"
                    ),
                    models.Index(
                        fields=["lesson_material"],
                        name="courses_doc_lesson__6cd0ce_idx",
                    ),
                ],
            },
        ),
    ]
