# Generated by Django 4.2.24 on 2025-11-11 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0035_migrate_quiz_assignment_to_manytomany"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["title", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["title", "created_at"]},
        ),
    ]
