# Generated by Django 4.2.24 on 2025-11-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0036_alter_assignment_options_alter_quiz_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomaterial",
            name="video_url",
            field=models.URLField(help_text="URL of the video (YouTube or other)"),
        ),
    ]
