# Generated by Django 4.2.24 on 2025-11-21 05:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0037_remove_video_url_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="graded_questions",
            field=models.JSONField(
                default=list,
                help_text="Individual question grades and feedback - list of {question_id, points_earned, points_possible, teacher_feedback/feedback, correct_answer (optional), is_correct (optional)}",
            ),
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "room_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique room code for students to join (e.g., 'MATH-AM-A')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the classroom is currently active",
                    ),
                ),
                (
                    "chat_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether chat is enabled in this classroom",
                    ),
                ),
                (
                    "board_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether virtual board is enabled in this classroom",
                    ),
                ),
                (
                    "video_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether video cam is enabled in this classroom",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_instance",
                    models.OneToOneField(
                        help_text="The class this classroom belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom",
                        to="courses.class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classroom",
                "verbose_name_plural": "Classrooms",
                "db_table": "classrooms",
                "ordering": ["class_instance__course__title", "class_instance__name"],
            },
        ),
    ]
