# Generated by Django 4.2.24 on 2025-11-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0039_add_tldraw_board_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classevent",
            name="meeting_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("jitsi", "Jitsi Meet"),
                    ("google-meet", "Google Meet"),
                    ("zoom", "Zoom"),
                    ("other", "Other"),
                ],
                help_text="Platform for live class meetings",
                max_length=20,
                null=True,
            ),
        ),
    ]
