# Generated by Django 4.2.24 on 2025-11-24 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0040_alter_classevent_meeting_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Classroom Board",
                        help_text="Board title/name",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Board description"),
                ),
                (
                    "allow_student_edit",
                    models.BooleanField(
                        default=False,
                        help_text="Whether students can draw/edit on the board",
                    ),
                ),
                (
                    "allow_student_create_pages",
                    models.BooleanField(
                        default=False, help_text="Whether students can create new pages"
                    ),
                ),
                (
                    "view_only_mode",
                    models.BooleanField(
                        default=False,
                        help_text="If True, students can only view (read-only mode)",
                    ),
                ),
                (
                    "current_page_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the currently active page",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.OneToOneField(
                        help_text="The classroom this board belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board",
                        to="courses.classroom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this board",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
                "db_table": "boards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_name",
                    models.CharField(
                        default="Page 1", help_text="Page name/title", max_length=200
                    ),
                ),
                (
                    "page_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order of this page within the board (for sorting)",
                    ),
                ),
                (
                    "state",
                    models.JSONField(
                        default=dict,
                        help_text="Full tldraw store snapshot (document state)",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number for conflict resolution"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        help_text="The board this page belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="courses.board",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_board_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_board_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Board Page",
                "verbose_name_plural": "Board Pages",
                "db_table": "board_pages",
                "ordering": ["board", "page_order", "created_at"],
                "unique_together": {("board", "page_order")},
            },
        ),
    ]
