# Generated by Django 4.2.24 on 2025-11-25 18:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0041_board_boardpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[("test", "Test"), ("exam", "Exam")], max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Instructions shown to students"
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Time limit in minutes (null = no limit)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "passing_score",
                    models.IntegerField(
                        default=50,
                        help_text="Minimum percentage to pass",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of attempts allowed",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order within course"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Assessment",
                "verbose_name_plural": "Course Assessments",
                "ordering": ["course", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseAssessmentQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField(help_text="The question text")),
                (
                    "order",
                    models.IntegerField(help_text="Question order within assessment"),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=1,
                        help_text="Points awarded for correct answer",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("fill_blank", "Fill in the Blank"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("matching", "Matching"),
                            ("ordering", "Ordering/Ranking"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict,
                        help_text="Question-specific content (options, answers, etc.)",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explanation shown after answering"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.courseassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Question",
                "verbose_name_plural": "Assessment Questions",
                "ordering": ["assessment", "order"],
                "indexes": [
                    models.Index(
                        fields=["assessment", "order"],
                        name="courses_cou_assessm_1a8a67_idx",
                    )
                ],
                "unique_together": {("assessment", "order")},
            },
        ),
        migrations.AddIndex(
            model_name="courseassessment",
            index=models.Index(
                fields=["course", "assessment_type"],
                name="courses_cou_course__e46ca8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="courseassessment",
            index=models.Index(
                fields=["course", "order"], name="courses_cou_course__74a992_idx"
            ),
        ),
    ]
