# Generated by Django 4.2.24 on 2025-11-27 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0042_courseassessment_courseassessmentquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classevent",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated assessment (if event type is test or exam)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.courseassessment",
            ),
        ),
        migrations.AlterField(
            model_name="classevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("meeting", "Meeting"),
                    ("project", "Project"),
                    ("break", "Break"),
                    ("test", "Test"),
                    ("exam", "Exam"),
                ],
                default="lesson",
                help_text="Type of event",
                max_length=20,
            ),
        ),
    ]
