# Generated by Django 4.2.24 on 2025-11-27 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0042_courseassessment_courseassessmentquestion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioVideoMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Stored filename in GCS (e.g., 'audio-video/uuid-filename.mp4')",
                        max_length=255,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename from user upload (e.g., 'My Lesson Video.mp4')",
                        max_length=255,
                    ),
                ),
                (
                    "file_url",
                    models.URLField(help_text="Full GCS URL to the audio/video file"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "file_extension",
                    models.CharField(
                        help_text="File extension (e.g., 'mp3', 'mp4', 'wav', 'ogg')",
                        max_length=10,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="MIME type (e.g., 'audio/mpeg', 'video/mp4', 'audio/wav')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson_material",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to LessonMaterial if this is part of a lesson",
                        limit_choices_to={"material_type": "audio"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_video_data",
                        to="courses.lessonmaterial",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher who uploaded this audio/video",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_audio_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio/Video Material",
                "verbose_name_plural": "Audio/Video Materials",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["file_url"], name="courses_aud_file_ur_069425_idx"
                    ),
                    models.Index(
                        fields=["file_extension"], name="courses_aud_file_ex_843f7d_idx"
                    ),
                    models.Index(
                        fields=["mime_type"], name="courses_aud_mime_ty_292d4f_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="courses_aud_uploade_dca442_idx"
                    ),
                    models.Index(
                        fields=["lesson_material"],
                        name="courses_aud_lesson__800092_idx",
                    ),
                ],
            },
        ),
    ]
