# Generated by Django 4.2.24 on 2025-11-30 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0043_add_test_exam_event_types"),
        ("courses", "0043_audiovideomaterial"),
    ]

    operations = []
