# Generated by Django 4.2.24 on 2025-11-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0044_merge_20251130_2116"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="ide_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether IDE is enabled in this classroom"
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="virtual_lab_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether virtual lab is enabled in this classroom",
            ),
        ),
    ]
