# Generated by Django 4.2.24 on 2025-12-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0045_classroom_ide_enabled_classroom_virtual_lab_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="required_computer_skills_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("any", "Any Level"),
                ],
                default="any",
                help_text="Required computer/technology experience level for this course. Used for assessment-based recommendations.",
                max_length=20,
            ),
        ),
    ]
