# Generated by Django 4.2.24 on 2025-12-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0046_course_required_computer_skills_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("fill_blank", "Fill in the Blank"),
                    ("short_answer", "Short Answer"),
                    ("essay", "Essay"),
                    ("matching", "Matching"),
                    ("ordering", "Ordering/Ranking"),
                    ("flashcard", "Flashcard"),
                    ("code", "Code"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="courseassessmentquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("fill_blank", "Fill in the Blank"),
                    ("short_answer", "Short Answer"),
                    ("essay", "Essay"),
                    ("matching", "Matching"),
                    ("ordering", "Ordering/Ranking"),
                    ("code", "Code"),
                ],
                max_length=20,
            ),
        ),
    ]
