# Generated by Django 4.2.24 on 2025-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0047_alter_assignmentquestion_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.URLField(
                blank=True,
                help_text="Course thumbnail image URL (optional, auto-generated)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.URLField(
                blank=True,
                help_text="Course cover image URL (optional, uploaded to GCS)",
                max_length=500,
                null=True,
            ),
        ),
    ]
