# Generated by Django 4.2.24 on 2025-12-18 20:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0015_codesnippet_class_instance_and_more"),
        ("courses", "0048_course_thumbnail_alter_course_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAssessmentSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("auto_submitted", "Auto-Submitted"),
                            ("graded", "Graded"),
                        ],
                        default="in_progress",
                        help_text="Submission status: in_progress, submitted, auto_submitted, or graded",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_limit_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Time limit when submission started",
                        null=True,
                    ),
                ),
                (
                    "time_remaining_seconds",
                    models.IntegerField(
                        blank=True, help_text="Remaining time in seconds", null=True
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict, help_text="Student answers for each question"
                    ),
                ),
                (
                    "is_graded",
                    models.BooleanField(
                        default=False, help_text="Has teacher graded this submission?"
                    ),
                ),
                (
                    "is_teacher_draft",
                    models.BooleanField(
                        default=False,
                        help_text="Is teacher currently working on grading this submission?",
                    ),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "points_earned",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Points earned by student",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "points_possible",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total points possible",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage score",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(
                        default=False, help_text="Did student pass the assessment?"
                    ),
                ),
                (
                    "instructor_feedback",
                    models.TextField(
                        blank=True, help_text="Teacher's feedback on the submission"
                    ),
                ),
                (
                    "feedback_checked",
                    models.BooleanField(
                        default=False, help_text="Has student seen the feedback?"
                    ),
                ),
                (
                    "feedback_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When student last checked feedback",
                        null=True,
                    ),
                ),
                (
                    "feedback_response",
                    models.TextField(
                        blank=True, help_text="Student's response to teacher feedback"
                    ),
                ),
                (
                    "graded_questions",
                    models.JSONField(
                        default=list,
                        help_text="Individual question grades and feedback - list of {question_id, points_earned, points_possible, teacher_feedback/feedback, correct_answer (optional), is_correct (optional)}",
                    ),
                ),
                (
                    "grading_history",
                    models.JSONField(
                        default=list, help_text="Audit trail of grading changes"
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="courses.courseassessment",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.enrolledcourse",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_course_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-started_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "assessment"],
                        name="courses_cou_student_e7d829_idx",
                    ),
                    models.Index(
                        fields=["enrollment", "submitted_at"],
                        name="courses_cou_enrollm_5e0f1e_idx",
                    ),
                    models.Index(
                        fields=["is_graded"], name="courses_cou_is_grad_05a665_idx"
                    ),
                    models.Index(
                        fields=["feedback_checked"],
                        name="courses_cou_feedbac_341c37_idx",
                    ),
                    models.Index(
                        fields=["status"], name="courses_cou_status_d35f87_idx"
                    ),
                ],
                "unique_together": {("student", "assessment", "attempt_number")},
            },
        ),
    ]
