# Generated by Django 4.2.24 on 2025-12-21 17:44

from django.db import migrations, models
import django.db.models.deletion


def create_submission_types(apps, schema_editor):
    """Create initial SubmissionType objects"""
    SubmissionType = apps.get_model('courses', 'SubmissionType')
    
    submission_types_data = [
        {
            'name': 'link',
            'display_name': 'Link/URL',
            'description': 'Students submit URLs (GitHub repositories, live websites, etc.)',
            'requires_file_upload': False,
            'requires_text_input': False,
            'requires_url_input': True,
            'is_active': True,
            'icon': 'external-link',
            'order': 1,
        },
        {
            'name': 'image',
            'display_name': 'Image',
            'description': 'Students upload image files (designs, screenshots, diagrams)',
            'requires_file_upload': True,
            'requires_text_input': False,
            'requires_url_input': False,
            'is_active': True,
            'icon': 'image',
            'order': 2,
        },
        {
            'name': 'video',
            'display_name': 'Video',
            'description': 'Students upload video files (presentations, demos, tutorials)',
            'requires_file_upload': True,
            'requires_text_input': False,
            'requires_url_input': False,
            'is_active': True,
            'icon': 'video',
            'order': 3,
        },
        {
            'name': 'audio',
            'display_name': 'Audio',
            'description': 'Students upload audio files (podcasts, voice notes, recordings)',
            'requires_file_upload': True,
            'requires_text_input': False,
            'requires_url_input': False,
            'is_active': True,
            'icon': 'mic',
            'order': 4,
        },
        {
            'name': 'file',
            'display_name': 'File Upload',
            'description': 'Students upload general files (documents, code files, etc.)',
            'requires_file_upload': True,
            'requires_text_input': False,
            'requires_url_input': False,
            'is_active': True,
            'icon': 'file',
            'order': 5,
        },
        {
            'name': 'note',
            'display_name': 'Text Note',
            'description': 'Students submit text-based content (essays, reflections, notes)',
            'requires_file_upload': False,
            'requires_text_input': True,
            'requires_url_input': False,
            'is_active': True,
            'icon': 'sticky-note',
            'order': 6,
        },
        {
            'name': 'code',
            'display_name': 'Code',
            'description': 'Students submit code (programming assignments, scripts)',
            'requires_file_upload': False,
            'requires_text_input': True,
            'requires_url_input': False,
            'is_active': True,
            'icon': 'code',
            'order': 7,
        },
        {
            'name': 'presentation',
            'display_name': 'Presentation',
            'description': 'Students submit presentation files (PowerPoint, PDF, etc.)',
            'requires_file_upload': True,
            'requires_text_input': False,
            'requires_url_input': False,
            'is_active': True,
            'icon': 'presentation',
            'order': 8,
        },
    ]
    
    for type_data in submission_types_data:
        SubmissionType.objects.get_or_create(
            name=type_data['name'],
            defaults=type_data
        )


def migrate_project_submission_types(apps, schema_editor):
    """Migrate Project submission_type from CharField to ForeignKey"""
    Project = apps.get_model('courses', 'Project')
    SubmissionType = apps.get_model('courses', 'SubmissionType')
    
    # Create a mapping of old string values to SubmissionType objects
    type_mapping = {}
    for submission_type in SubmissionType.objects.all():
        type_mapping[submission_type.name] = submission_type
    
    # Migrate each project
    for project in Project.objects.all():
        if project.submission_type_old:  # Using the old field name temporarily
            submission_type_name = project.submission_type_old
            if submission_type_name in type_mapping:
                project.submission_type_new = type_mapping[submission_type_name]
                project.save(update_fields=['submission_type_new'])
            else:
                # Default to 'note' if type not found
                default_type = type_mapping.get('note')
                if default_type:
                    project.submission_type_new = default_type
                    project.save(update_fields=['submission_type_new'])


def migrate_classevent_submission_types(apps, schema_editor):
    """Migrate ClassEvent submission_type from CharField to ForeignKey"""
    ClassEvent = apps.get_model('courses', 'ClassEvent')
    SubmissionType = apps.get_model('courses', 'SubmissionType')
    
    # Create a mapping of old string values to SubmissionType objects
    type_mapping = {}
    for submission_type in SubmissionType.objects.all():
        type_mapping[submission_type.name] = submission_type
    
    # Migrate each class event
    for event in ClassEvent.objects.all():
        if event.submission_type_old:  # Using the old field name temporarily
            submission_type_name = event.submission_type_old
            if submission_type_name in type_mapping:
                event.submission_type_new = type_mapping[submission_type_name]
                event.save(update_fields=['submission_type_new'])


def reverse_migrate_project_submission_types(apps, schema_editor):
    """Reverse migration - convert ForeignKey back to CharField"""
    Project = apps.get_model('courses', 'Project')
    
    for project in Project.objects.all():
        if project.submission_type_new:
            project.submission_type_old = project.submission_type_new.name
            project.save(update_fields=['submission_type_old'])


def reverse_migrate_classevent_submission_types(apps, schema_editor):
    """Reverse migration - convert ForeignKey back to CharField"""
    ClassEvent = apps.get_model('courses', 'ClassEvent')
    
    for event in ClassEvent.objects.all():
        if event.submission_type_new:
            event.submission_type_old = event.submission_type_new.name
            event.save(update_fields=['submission_type_old'])


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0050_merge_20251219_1437"),
    ]

    operations = [
        # Step 1: Create SubmissionType model
        migrations.CreateModel(
            name="SubmissionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name (e.g., 'link', 'code', 'image')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="User-friendly display name (e.g., 'Link/URL', 'Code Submission')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this submission type"
                    ),
                ),
                (
                    "requires_file_upload",
                    models.BooleanField(
                        default=False,
                        help_text="Does this submission type require file upload?",
                    ),
                ),
                (
                    "requires_text_input",
                    models.BooleanField(
                        default=False,
                        help_text="Does this submission type require text input?",
                    ),
                ),
                (
                    "requires_url_input",
                    models.BooleanField(
                        default=False,
                        help_text="Does this submission type require URL input?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this submission type currently available?",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for UI display",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in admin and forms"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Submission Type",
                "verbose_name_plural": "Submission Types",
                "ordering": ["order", "display_name"],
            },
        ),
        # Step 2: Populate SubmissionType objects
        migrations.RunPython(create_submission_types, migrations.RunPython.noop),
        # Step 3: Rename old CharField to temporary name for Project
        migrations.RenameField(
            model_name="project",
            old_name="submission_type",
            new_name="submission_type_old",
        ),
        # Step 4: Add new ForeignKey field for Project (nullable initially)
        migrations.AddField(
            model_name="project",
            name="submission_type_new",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects_temp",
                to="courses.submissiontype",
            ),
        ),
        # Step 5: Migrate data for Project
        migrations.RunPython(migrate_project_submission_types, reverse_migrate_project_submission_types),
        # Step 6: Remove old CharField and rename new field for Project
        migrations.RemoveField(
            model_name="project",
            name="submission_type_old",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="submission_type_new",
            new_name="submission_type",
        ),
        # Step 7: Make Project.submission_type non-nullable
        migrations.AlterField(
            model_name="project",
            name="submission_type",
            field=models.ForeignKey(
                help_text="Type of submission expected from students",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="courses.submissiontype",
            ),
        ),
        # Step 8: Rename old CharField to temporary name for ClassEvent
        migrations.RenameField(
            model_name="classevent",
            old_name="submission_type",
            new_name="submission_type_old",
        ),
        # Step 9: Add new ForeignKey field for ClassEvent (nullable)
        migrations.AddField(
            model_name="classevent",
            name="submission_type_new",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_events_temp",
                to="courses.submissiontype",
            ),
        ),
        # Step 10: Migrate data for ClassEvent
        migrations.RunPython(migrate_classevent_submission_types, reverse_migrate_classevent_submission_types),
        # Step 11: Remove old CharField and rename new field for ClassEvent
        migrations.RemoveField(
            model_name="classevent",
            name="submission_type_old",
        ),
        migrations.RenameField(
            model_name="classevent",
            old_name="submission_type_new",
            new_name="submission_type",
        ),
        # Step 12: Finalize ClassEvent field
        migrations.AlterField(
            model_name="classevent",
            name="submission_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Expected submission type for project events",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_events",
                to="courses.submissiontype",
            ),
        ),
    ]
