# Generated by Django 4.2.24 on 2025-12-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0051_submissiontype_alter_classevent_submission_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsubmission",
            name="share_token",
            field=models.CharField(
                blank=True,
                help_text="Unique token for sharing project submission publicly",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
