# Generated by Django 4.2.24 on 2025-12-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0052_add_share_token_to_project_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="type",
            field=models.CharField(
                choices=[
                    ("live_class", "Live Class"),
                    ("video_audio", "Video/Audio Lesson"),
                    ("text_lesson", "Text Lesson"),
                    ("tutorx", "TutorX Lesson"),
                ],
                max_length=20,
            ),
        ),
    ]
