# Generated by Django 4.2.24 on 2026-01-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0053_alter_lesson_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="landing_page_url",
            field=models.CharField(
                blank=True,
                help_text="Custom landing page URL for marketing. If empty, will auto-generate from course title and ID. Format: /courses/slug-uuid?landing=true",
                max_length=500,
                null=True,
            ),
        ),
    ]
