# Generated by Django 4.2.24 on 2026-01-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0054_course_landing_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="submission_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of submission expected from students (set when scheduling as ClassEvent)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="courses.submissiontype",
            ),
        ),
    ]
