# Generated by Django 4.2.24 on 2026-01-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0055_make_project_submission_type_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("live", "Live"),
                    ("self_paced", "Self-paced"),
                    ("hybrid", "Hybrid (Live + Self-paced)"),
                ],
                default="live",
                help_text="How this course is delivered: live, self-paced, or hybrid",
                max_length=20,
            ),
        ),
    ]
