# Generated by Django 4.2.24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0056_course_delivery_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Module title", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Optional module description")),
                ("order", models.PositiveIntegerField(help_text="Order of this module within the course")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="modules", to="courses.course")),
            ],
            options={
                "ordering": ["course", "order"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional module this lesson belongs to. If module is deleted, lesson stays in course with module=None.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="courses.module",
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(fields=["course", "order"], name="courses_module_course_order_idx"),
        ),
    ]
