# Generated by Django 4.2.24 on 2026-02-15 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0057_add_module_and_lesson_module_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="module",
            new_name="courses_mod_course__20183c_idx",
            old_name="courses_module_course_order_idx",
        ),
    ]
