# Generated by Django 4.2.24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0058_rename_courses_module_course_order_idx_courses_mod_course__20183c_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="return_feedback",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="When status is draft: optional feedback from teacher when they returned the submission. List of {question_id, feedback}.",
                null=True,
            ),
        ),
    ]
