# Generated by Django 4.2.24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0059_assignmentsubmission_return_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="return_for_revision_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of times this submission has been returned for revision (TutorX/auto). Used with assignment.max_attempts to cap returns.",
            ),
        ),
    ]
