# Generated by Django 4.2.24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0060_assignmentsubmission_return_for_revision_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="tutorx_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="For TutorX lessons: BlockNote blocks as JSON string. Same format as book page content.",
            ),
        ),
    ]
