# Generated by Django 4.2.24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0063_projectsubmission_file_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseassessmentsubmission",
            name="return_feedback",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="When status is in_progress after teacher return: optional feedback per question. List of {question_id, feedback}.",
                null=True,
            ),
        ),
    ]
