# Generated by Django 4.2.24 on 2026-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0067_course_trial_enabled_course_trial_period_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="promo_video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional YouTube URL for the ad landing page hero. Replaces course image and header text when set.",
                max_length=500,
                verbose_name="Promo video URL (YouTube)",
            ),
        ),
    ]
