# Generated by Django 4.2.24 on 2026-07-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0069_lesson_show_ask_ai"),
    ]

    operations = [
        migrations.AddField(
            model_name="classevent",
            name="all_day",
            field=models.BooleanField(
                default=False,
                help_text="When True, event is date-based with no specific clock time",
            ),
        ),
        migrations.AddField(
            model_name="classevent",
            name="is_schedule_generated",
            field=models.BooleanField(
                default=False,
                help_text="True when this event was generated from an EnrollmentSchedule cadence",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="all_day",
            field=models.BooleanField(
                default=False,
                help_text="When True, session is date/day-based with no clock time",
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="end_time",
            field=models.TimeField(
                blank=True, help_text="Session end time (null when all_day)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Session start time (null when all_day)",
                null=True,
            ),
        ),
    ]
