# Generated by Django 4.2.24 on 2026-04-02 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communication", "0005_smsroutinglog_related_outbound"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="messagetemplate",
            new_name="message_tem_channel_ffe528_idx",
            old_name="message_temp_channel_0b7b2d_idx",
        ),
        migrations.RenameIndex(
            model_name="smsroutinglog",
            new_name="sms_routing_student_a140fb_idx",
            old_name="sms_routing_student_0f3b0a_idx",
        ),
        migrations.AlterField(
            model_name="smsroutinglog",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher on outbound; set on inbound after routing (optional until processed).",
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_routing_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
