# Generated by Django 4.2.24 on 2025-09-21 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("live_chat", "Live Chat"),
                            ("email", "Email Support"),
                            ("phone", "Phone Support"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title for the contact method", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the contact method"),
                ),
                (
                    "availability",
                    models.CharField(
                        help_text="When this method is available", max_length=100
                    ),
                ),
                (
                    "response_time",
                    models.CharField(help_text="Expected response time", max_length=50),
                ),
                (
                    "action_text",
                    models.CharField(help_text="Button or action text", max_length=100),
                ),
                (
                    "action_value",
                    models.CharField(
                        help_text="Email, phone number, or URL", max_length=200
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon class or identifier", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="purple",
                        help_text="Color theme for the method",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Method",
                "verbose_name_plural": "Contact Methods",
                "ordering": ["order", "type"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional category grouping",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "question"],
            },
        ),
        migrations.CreateModel(
            name="SupportHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="e.g., Mon-Fri, Weekends, Emergency", max_length=50
                    ),
                ),
                (
                    "hours",
                    models.CharField(
                        help_text="e.g., 9AM-6PM EST, 24/7", max_length=50
                    ),
                ),
                (
                    "is_emergency",
                    models.BooleanField(
                        default=False, help_text="Mark as emergency/24-7 service"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Support Hours",
                "verbose_name_plural": "Support Hours",
                "ordering": ["order", "period"],
            },
        ),
        migrations.CreateModel(
            name="SupportTeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(help_text="Job title", max_length=100)),
                ("responsibilities", models.TextField(help_text="What they help with")),
                ("email", models.EmailField(help_text="Contact email", max_length=254)),
                (
                    "avatar_initials",
                    models.CharField(
                        help_text="Initials for avatar display", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Support Team Member",
                "verbose_name_plural": "Support Team Members",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("technical", "Technical Support"),
                            ("billing", "Billing Question"),
                            ("course_guidance", "Course Guidance"),
                            ("enrollment", "Enrollment Help"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "child_age",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3-5", "3-5 years"),
                            ("6-8", "6-8 years"),
                            ("9-12", "9-12 years"),
                            ("13-15", "13-15 years"),
                            ("16-18", "16-18 years"),
                            ("adult", "Adult"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "wants_updates",
                    models.BooleanField(
                        default=False,
                        help_text="Wants to receive updates about new courses",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "response_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about the response"
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who responded to this inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
