# Generated by Django 4.2.24 on 2025-12-03 21:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_name", models.CharField(max_length=100)),
                ("parent_contact", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("student_name", models.CharField(max_length=100)),
                (
                    "student_age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(18),
                        ]
                    ),
                ),
                ("school_level", models.CharField(blank=True, max_length=50)),
                ("city_country", models.CharField(blank=True, max_length=100)),
                (
                    "interest_areas",
                    models.JSONField(
                        default=list, help_text="List of selected STEM interest areas"
                    ),
                ),
                ("has_coding_experience", models.BooleanField(default=False)),
                (
                    "coding_tools",
                    models.TextField(
                        blank=True, help_text="Tools/languages used if has experience"
                    ),
                ),
                (
                    "device_access",
                    models.JSONField(
                        default=list, help_text="List of available devices"
                    ),
                ),
                (
                    "availability_days",
                    models.JSONField(
                        default=list, help_text="List of available days of the week"
                    ),
                ),
                ("preferred_time_slots", models.CharField(blank=True, max_length=100)),
                (
                    "goals",
                    models.TextField(
                        blank=True,
                        help_text="What parent wants child to gain from program",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("enrolled", "Enrolled"),
                            ("not_interested", "Not Interested"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "response_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about follow-up"
                    ),
                ),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contacted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who contacted this submission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Submission",
                "verbose_name_plural": "Assessment Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
