# Generated by Django 4.2.24 on 2025-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_assessmentsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsubmission",
            name="computer_skills_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                help_text="Computer/technology experience level",
                max_length=20,
            ),
        ),
    ]
