# Generated by Django 4.2.24 on 2025-12-29 02:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0052_add_share_token_to_project_submission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="My Portfolio",
                        help_text="Portfolio title",
                        max_length=200,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Student's bio/about section"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Student's profile image",
                        null=True,
                        upload_to="portfolio/profiles/",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the portfolio is publicly accessible",
                    ),
                ),
                (
                    "custom_url",
                    models.SlugField(
                        blank=True,
                        help_text="Custom URL slug (e.g., 'john-doe')",
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Custom URL can only contain lowercase letters, numbers, and hyphens",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        default="default",
                        help_text="Portfolio theme/style",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        help_text="The student who owns this portfolio",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Portfolios",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Portfolio title (can override project title)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Student-written portfolio description"),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item is featured (pinned to top)",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Custom ordering (lower numbers appear first)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Project category (e.g., 'Python', 'Web Development')",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of tags (e.g., ['OOP', 'APIs', 'React'])",
                    ),
                ),
                (
                    "skills_demonstrated",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of skills (e.g., ['Problem Solving', 'UI/UX'])",
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        help_text="Custom thumbnail image for this portfolio item",
                        null=True,
                        upload_to="portfolio/thumbnails/",
                    ),
                ),
                (
                    "screenshots",
                    models.JSONField(
                        blank=True, default=list, help_text="Array of screenshot URLs"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is visible in the portfolio",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        help_text="The portfolio this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="portfolio.portfolio",
                    ),
                ),
                (
                    "project_submission",
                    models.ForeignKey(
                        help_text="The project submission this portfolio item represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="courses.projectsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Portfolio Items",
                "ordering": ["-featured", "order", "-created_at"],
                "unique_together": {("portfolio", "project_submission")},
            },
        ),
    ]
