# Generated by Django 4.2.23 on 2025-08-23 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0007_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("behavioral", "Behavioral"),
                            ("personal", "Personal"),
                            ("parent_communication", "Parent Communication"),
                            ("medical", "Medical/Health"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "is_private",
                    models.BooleanField(
                        default=True, help_text="Private notes only visible to teacher"
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(
                        default=False, help_text="Mark as important for quick reference"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_notes",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentGrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("project", "Project"),
                            ("exam", "Exam"),
                            ("participation", "Participation"),
                            ("homework", "Homework"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the assessment", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("points_earned", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "points_possible",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "letter_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+ (97-100)"),
                            ("A", "A (93-96)"),
                            ("A-", "A- (90-92)"),
                            ("B+", "B+ (87-89)"),
                            ("B", "B (83-86)"),
                            ("B-", "B- (80-82)"),
                            ("C+", "C+ (77-79)"),
                            ("C", "C (73-76)"),
                            ("C-", "C- (70-72)"),
                            ("D+", "D+ (67-69)"),
                            ("D", "D (63-66)"),
                            ("D-", "D- (60-62)"),
                            ("F", "F (0-59)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("teacher_comments", models.TextField(blank=True)),
                (
                    "private_notes",
                    models.TextField(
                        blank=True, help_text="Private notes for teacher only"
                    ),
                ),
                ("assigned_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                ("graded_date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_grades",
                        to="courses.course",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graded_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.lesson",
                    ),
                ),
                (
                    "quiz_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.quizattempt",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_grades",
                "ordering": ["-graded_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentCommunication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone Call"),
                            ("meeting", "In-Person Meeting"),
                            ("message", "Platform Message"),
                            ("letter", "Written Letter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("progress_update", "Progress Update"),
                            ("behavior_concern", "Behavior Concern"),
                            ("academic_concern", "Academic Concern"),
                            ("positive_feedback", "Positive Feedback"),
                            ("schedule_change", "Schedule Change"),
                            ("general_inquiry", "General Inquiry"),
                            ("parent_request", "Parent Request"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("contacted_student", models.BooleanField(default=False)),
                ("contacted_parent", models.BooleanField(default=False)),
                ("parent_email", models.EmailField(blank=True, max_length=254)),
                ("parent_phone", models.CharField(blank=True, max_length=20)),
                ("response_received", models.BooleanField(default=False)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("response_content", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_completed", models.BooleanField(default=False)),
                ("sent_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_communications",
                "ordering": ["-sent_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentBehavior",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "behavior_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("participation", "Class Participation"),
                            ("homework", "Homework Completion"),
                            ("respect", "Respectful Behavior"),
                            ("helping", "Helping Others"),
                            ("leadership", "Leadership"),
                            ("creativity", "Creativity"),
                            ("disruption", "Class Disruption"),
                            ("tardiness", "Tardiness"),
                            ("incomplete_work", "Incomplete Work"),
                            ("disrespect", "Disrespectful Behavior"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Minor"), (2, "Moderate"), (3, "Major")],
                        default=1,
                        help_text="1=Minor, 2=Moderate, 3=Major",
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(blank=True, help_text="What action was taken"),
                ),
                ("parent_contacted", models.BooleanField(default=False)),
                ("parent_contact_date", models.DateTimeField(blank=True, null=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("incident_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_records",
                        to="courses.class",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_behaviors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_behavior",
                "ordering": ["-incident_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about attendance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="courses.class",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_attendance",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("student", "class_session", "date")},
            },
        ),
    ]
