# Generated by Django 4.2.23 on 2025-08-25 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentnote",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentnote",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentgrade",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_grades",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="studentgrade",
            name="graded_by",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graded_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentgrade",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="studentgrade",
            name="quiz_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.quizattempt",
            ),
        ),
        migrations.AddField(
            model_name="studentgrade",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentcommunication",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentcommunication",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_communications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentbehavior",
            name="class_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavior_records",
                to="courses.class",
            ),
        ),
        migrations.AddField(
            model_name="studentbehavior",
            name="reported_by",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_behaviors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentbehavior",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavior_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="class_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="courses.class",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="recorded_by",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recorded_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrolledcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_enrollments",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="enrolledcourse",
            name="current_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Current lesson the student is working on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_students",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="enrolledcourse",
            name="enrolled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher or admin who enrolled the student",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrolled_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrolledcourse",
            name="student_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_enrollments",
                to="users.studentprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("student", "class_session", "date")},
        ),
        migrations.AddIndex(
            model_name="enrolledcourse",
            index=models.Index(
                fields=["student_profile", "status"],
                name="enrolled_co_student_e5b83f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrolledcourse",
            index=models.Index(
                fields=["course", "status"], name="enrolled_co_course__6e348a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrolledcourse",
            index=models.Index(
                fields=["enrollment_date"], name="enrolled_co_enrollm_d44cbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrolledcourse",
            index=models.Index(
                fields=["last_accessed"], name="enrolled_co_last_ac_cced70_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrolledcourse",
            unique_together={("student_profile", "course")},
        ),
    ]
