# Generated by Django 4.2.23 on 2025-08-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_enrolledcourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgrade",
            name="graded_questions",
            field=models.JSONField(
                default=list,
                help_text="Individual question grades and feedback - list of {question_id, is_correct, teacher_feedback, points_earned, points_possible}",
            ),
        ),
    ]
