# Generated by Django 4.2.23 on 2025-08-30 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_enrolledcourse_highest_quiz_score_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teacherassessment",
            unique_together=set(),
        ),
    ]
