# Generated by Django 4.2.23 on 2025-09-02 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_quizquestionfeedback_quizattemptfeedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrolledcourse",
            name="average_quiz_score",
        ),
    ]
