# Generated by Django 4.2.23 on 2025-09-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0006_remove_enrolledcourse_average_quiz_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolledcourse",
            name="average_quiz_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
