# Generated by Django 4.2.23 on 2025-09-03 20:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_add_lesson_type_to_classevent"),
        ("student", "0007_enrolledcourse_average_quiz_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLessonProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("locked", "Locked"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_spent",
                    models.IntegerField(default=0, help_text="Time spent in minutes"),
                ),
                (
                    "progress_data",
                    models.JSONField(
                        default=dict,
                        help_text="Lesson-specific progress data (video position, reading progress, etc.)",
                    ),
                ),
                ("quiz_attempts_count", models.IntegerField(default=0)),
                ("quiz_passed", models.BooleanField(default=False)),
                (
                    "best_quiz_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Best quiz score as percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to="student.enrolledcourse",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Lesson Progress",
                "verbose_name_plural": "Student Lesson Progress",
                "ordering": ["lesson__order"],
                "unique_together": {("enrollment", "lesson")},
            },
        ),
    ]
