# Generated by Django 4.2.24 on 2025-09-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0008_studentlessonprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherassessment",
            name="viewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the student first viewed this assessment",
                null=True,
            ),
        ),
    ]
