# Generated by Django 4.2.24 on 2025-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0009_teacherassessment_viewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolledcourse",
            name="average_assignment_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average assignment score percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enrolledcourse",
            name="total_assignments_graded",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
