# Generated by Django 4.2.24 on 2025-10-08 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0010_enrolledcourse_average_assignment_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrolledcourse",
            name="total_assignments_graded",
        ),
    ]
