# Generated by Django 4.2.24 on 2025-11-17 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_studentweeklyperformance"),
        ("student", "0011_remove_enrolledcourse_total_assignments_graded"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[("parent", "Parent"), ("student", "Student")],
                        default="parent",
                        help_text="Whether messages are for parent or student",
                        max_length=10,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Optional conversation topic/subject",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of most recent message (for sorting)",
                        null=True,
                    ),
                ),
                (
                    "student_profile",
                    models.ForeignKey(
                        help_text="Student profile this conversation is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="users.studentprofile",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher in this conversation",
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When message was read (null if unread)",
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Conversation this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="student.conversation",
                    ),
                ),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who read this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent this message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "-created_at"],
                        name="messages_convers_38b855_idx",
                    ),
                    models.Index(
                        fields=["conversation", "read_at"],
                        name="messages_convers_f33bac_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["student_profile", "recipient_type", "-last_message_at"],
                name="conversatio_student_d9485b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["teacher", "recipient_type", "-last_message_at"],
                name="conversatio_teacher_2430ba_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("student_profile", "teacher", "recipient_type")},
        ),
    ]
