# Generated by Django 4.2.24 on 2025-11-17 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0037_remove_video_url_unique_constraint"),
        ("users", "0005_studentweeklyperformance"),
        ("student", "0012_conversation_message_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="conversation",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Course this conversation is about (null for general conversations)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="courses.course",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={
                ("student_profile", "teacher", "recipient_type", "course")
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["course", "student_profile", "-last_message_at"],
                name="conversatio_course__3350e5_idx",
            ),
        ),
    ]
