# Generated by Django 4.2.24 on 2025-12-05 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0013_alter_conversation_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the code snippet",
                        max_length=200,
                    ),
                ),
                ("code", models.TextField(help_text="The actual code content")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("json", "JSON"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("c", "C"),
                            ("other", "Other"),
                        ],
                        default="python",
                        help_text="Programming language",
                        max_length=50,
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this code snippet is shareable (default: True)",
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        help_text="Unique token for sharing (auto-generated)",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student who created this code snippet",
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_snippets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Code Snippet",
                "verbose_name_plural": "Code Snippets",
                "db_table": "code_snippets",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-updated_at"],
                        name="code_snippe_student_6b61de_idx",
                    ),
                    models.Index(
                        fields=["share_token"], name="code_snippe_share_t_d88927_idx"
                    ),
                    models.Index(
                        fields=["language"], name="code_snippe_languag_15c19c_idx"
                    ),
                    models.Index(
                        fields=["is_shared"], name="code_snippe_is_shar_94e95d_idx"
                    ),
                ],
            },
        ),
    ]
