# Generated by Django 4.2.24 on 2025-12-06 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0046_course_required_computer_skills_level"),
        ("student", "0014_codesnippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesnippet",
            name="class_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="Class this snippet is associated with (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_snippets",
                to="courses.class",
            ),
        ),
        migrations.AddField(
            model_name="codesnippet",
            name="is_teacher_snippet",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is a teacher-created snippet (visible to all students in the lesson)",
            ),
        ),
        migrations.AddField(
            model_name="codesnippet",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Lesson this snippet is associated with (for teacher snippets)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_snippets",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="codesnippet",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher who created this code snippet (for lesson examples)",
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_code_snippets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="codesnippet",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="Student who created this code snippet (null for teacher snippets)",
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_snippets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
