# Generated by Django 4.2.24 on 2026-01-29 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0016_add_css_file_url_to_codesnippet"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="codesnippet",
            new_name="code_snippe_css_fil_a579bb_idx",
            old_name="student_cod_css_fil_idx",
        ),
    ]
