# Generated by Django 4.2.24 on 2026-05-05 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0019_add_text_language_and_text_file_url"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="codesnippet",
            new_name="code_snippe_text_fi_017fe0_idx",
            old_name="student_cod_text_fil_idx",
        ),
    ]
