# Generated by Django 4.2.24 on 2026-07-20 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0070_classsession_all_day_enrollment_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "student",
            "0020_rename_student_cod_text_fil_idx_code_snippe_text_fi_017fe0_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        help_text="How often learning slots occur",
                        max_length=20,
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="For weekly: list of weekdays 0=Monday .. 6=Sunday. Empty for daily.",
                    ),
                ),
                (
                    "all_day",
                    models.BooleanField(
                        default=True,
                        help_text="When True, slots have no clock time (date-only ClassEvents)",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Optional start time when all_day is False",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Optional end time when all_day is False",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IANA timezone for generating dated events",
                        max_length=63,
                    ),
                ),
                (
                    "horizon_days",
                    models.PositiveIntegerField(
                        default=21,
                        help_text="How many days ahead to materialize ClassEvents",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Private class used to hold generated ClassEvents for this enrollment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_schedules",
                        to="courses.class",
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        help_text="Enrollment this cadence belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="student.enrolledcourse",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_enrollment_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment Schedule",
                "verbose_name_plural": "Enrollment Schedules",
                "db_table": "enrollment_schedules",
            },
        ),
    ]
