# Generated by Django 4.2.24 on 2026-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0024_add_esp32_language_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentschedule",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Optional end time when all_day is False (shared fallback when weekday_slots empty)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentschedule",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Optional start time when all_day is False (shared fallback when weekday_slots empty)",
                null=True,
            ),
        ),
    ]
