# Generated by Django 4.2.24 on 2025-11-03 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("course_generation", "Course Generation"),
                            ("lesson_content", "Lesson Content"),
                            ("quiz_questions", "Quiz Questions"),
                            ("assignment_questions", "Assignment Questions"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context like course_id, lesson_id, etc.",
                    ),
                ),
                (
                    "messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Conversation messages array",
                    ),
                ),
                (
                    "generated_content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Final structured output from AI",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether conversation is still active"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Conversation",
                "verbose_name_plural": "AI Conversations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "conversation_type"],
                        name="ai_aiconver_user_id_1f7ebd_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_aiconver_created_4ce055_idx"
                    ),
                ],
            },
        ),
    ]
