# Generated by Django 4.2.24 on 2025-11-03 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("course_generation", "Course Generation"),
                            ("lesson_content", "Lesson Content"),
                            ("quiz_questions", "Quiz Questions"),
                            ("assignment_questions", "Assignment Questions"),
                        ],
                        help_text="Type of prompt (one per type)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "system_instruction",
                    models.TextField(
                        help_text="System-level instruction for the AI model (e.g., 'You are an expert educational content creator...')"
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        help_text="Prompt template. Use placeholders: {user_request}, {context}, {age_range}, {level}, etc."
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        help_text="Expected output schema as JSON (e.g., {'type': 'object', 'properties': {...}})"
                    ),
                ),
                (
                    "schema_description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of what the schema expects",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this prompt is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this prompt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this prompt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prompt",
                "verbose_name_plural": "AI Prompts",
                "ordering": ["prompt_type"],
            },
        ),
    ]
