# Generated by Django 4.2.24 on 2025-11-10 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0002_aiprompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier (e.g., 'quiz_generation', 'assignment_generation', 'course_introduction')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Quiz Generation', 'Assignment Generation')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this template is used for"
                    ),
                ),
                (
                    "default_system_instruction",
                    models.TextField(
                        help_text="Default system instruction shown to teachers. They can override this."
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="gemini-2.0-flash-001",
                        help_text="Gemini model to use",
                        max_length=100,
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7, help_text="Default temperature (0.0-1.0)"
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True,
                        help_text="Max tokens (null = use model's default)",
                        null=True,
                    ),
                ),
                (
                    "response_schema",
                    models.JSONField(
                        help_text="JSON Schema defining the expected output structure"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prompt_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_prompt_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prompt Template",
                "verbose_name_plural": "AI Prompt Templates",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="SchemaField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_key",
                    models.CharField(
                        help_text="JSON key name (e.g., 'title', 'question_text')",
                        max_length=100,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("array", "Array"),
                            ("object", "Object"),
                        ],
                        help_text="JSON Schema type",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Field description shown to AI"),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Whether this field is required"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display/order position"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_fields",
                        to="ai.aiprompttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Field",
                "verbose_name_plural": "Schema Fields",
                "ordering": ["template", "order", "field_key"],
                "unique_together": {("template", "field_key")},
            },
        ),
    ]
