# Generated by Django 4.2.24 on 2025-11-10 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_aiprompttemplate_schemafield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aiprompttemplate",
            name="response_schema",
        ),
        migrations.DeleteModel(
            name="SchemaField",
        ),
    ]
