# Generated by Django 4.2.24 on 2025-12-01 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_system_instructions(apps, schema_editor):
    """Migrate existing default_system_instruction data to SystemInstruction model"""
    AIPromptTemplate = apps.get_model('ai', 'AIPromptTemplate')
    SystemInstruction = apps.get_model('ai', 'SystemInstruction')
    
    for template in AIPromptTemplate.objects.all():
        if template.default_system_instruction:
            # Create SystemInstruction from existing default_system_instruction
            instruction_name = f"{template.name}_system_instruction"
            system_instruction = SystemInstruction.objects.create(
                name=instruction_name,
                version=1,
                content=template.default_system_instruction,
                description=f"Migrated from default_system_instruction for {template.display_name}",
                is_active=True,
                created_by=template.created_by,
                last_modified_by=template.last_modified_by
            )
            # Link the template to the new SystemInstruction
            template.system_instruction = system_instruction
            template.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0004_remove_aiprompttemplate_response_schema_and_more"),
    ]

    operations = [
        # Step 1: Create SystemInstruction model first
        migrations.CreateModel(
            name="SystemInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Identifier for this system instruction (e.g., 'quiz_generation_system_instruction')",
                        max_length=100,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Version number for this instruction (auto-increments per name)",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual system instruction text"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what changed in this version",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active version",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_system_instructions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_system_instructions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Instruction",
                "verbose_name_plural": "System Instructions",
                "ordering": ["name", "-version"],
            },
        ),
        # Step 2: Add the ForeignKey field (nullable for now)
        migrations.AddField(
            model_name="aiprompttemplate",
            name="system_instruction",
            field=models.ForeignKey(
                blank=True,
                help_text="Versioned system instruction. Teachers can override this when generating content.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompt_templates",
                to="ai.systeminstruction",
            ),
        ),
        # Step 3: Migrate existing data
        migrations.RunPython(migrate_system_instructions, migrations.RunPython.noop),
        # Step 4: Remove the old field
        migrations.RemoveField(
            model_name="aiprompttemplate",
            name="default_system_instruction",
        ),
        # Step 5: Add indexes and constraints
        migrations.AddIndex(
            model_name="systeminstruction",
            index=models.Index(
                fields=["name", "is_active"], name="ai_systemin_name_26e36b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systeminstruction",
            index=models.Index(
                fields=["name", "-version"], name="ai_systemin_name_8ea1d3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="systeminstruction",
            unique_together={("name", "version")},
        ),
    ]
