# Generated by Django 4.2.24 on 2026-09-14 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0073_lessonvideoupload'),
        ('ai', '0006_aiprompttemplate_model_name_use_env_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacherPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment')], max_length=20)),
                ('instruction', models.TextField(blank=True, help_text='Optional extra instructions appended to the global base prompt.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ai_prompts', to='courses.course')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_ai_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Teacher Prompt',
                'verbose_name_plural': 'Course Teacher Prompts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['course', 'teacher', 'kind'], name='ai_coursete_course__3baacc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='courseteacherprompt',
            constraint=models.UniqueConstraint(fields=('course', 'teacher', 'kind'), name='unique_course_teacher_prompt_kind'),
        ),
    ]
